const AmbassadorProfile = require("../models/AmbassadorProfile");
const ReferralAttribution = require("../models/ReferralAttribution");
const CommissionLedger = require("../models/CommissionLedger");
const Contact = require("../models/Contact");
const CoachingApplication = require("../models/CoachingApplication");
const Enrollment = require("../models/Enrollment");
const CrmActivity = require("../models/CrmActivity");
const User = require("../models/User"); const WorkspaceConfig = require("../models/WorkspaceConfig"); const welcome = require("./ambassadorWelcomeService");
const deps = { AmbassadorProfile, ReferralAttribution, CommissionLedger, Contact, CoachingApplication, Enrollment, CrmActivity, User, WorkspaceConfig };
function fail(message, code) { const error = new Error(message); error.code = code; return error; }
function referralUrl(code) { return `${String(process.env.PUBLIC_FRONTEND_URL || process.env.FRONTEND_URL || "http://localhost:5173").replace(/\/$/, "")}/ref/${encodeURIComponent(code)}`; }
async function ownProfile({ workspaceId, userId }, models = deps) { const profile = await models.AmbassadorProfile.findOne({ workspaceId, userId, status: "active" }).populate("userId", require("./userProfileService").selection).lean(); if (!profile) throw fail("Active ambassador profile not found", "AMBASSADOR_NOT_FOUND"); const identity = require("./userProfileService").resolveProfile(profile.userId, profile); return { ...profile, ...identity, displayName: identity.name, publicLocation: identity.location, referralUrl: referralUrl(profile.referralSlug || profile.referralCode) }; }
async function ownProfileWithCompleteness({ workspaceId, userId }, models = deps) { const [profile, config] = await Promise.all([ownProfile({ workspaceId, userId }, models), models.WorkspaceConfig.findOne({ workspaceId, key: "primary" }).lean()]); return { ...profile, completeness: welcome.completeness(profile, profile.userId, config?.ambassadorOnboarding?.requiredFields) }; }
async function updateOwnProfile({ workspaceId, userId, changes }, models = deps) {
  await ownProfile({ workspaceId, userId }, models);
  const identity = { ...changes };
  delete identity.notificationPreferences;
  if (identity.displayName !== undefined) { identity.name = identity.displayName; delete identity.displayName; }
  if (identity.publicLocation !== undefined) { identity.location = identity.publicLocation; delete identity.publicLocation; }
  await require("./userProfileService").save({ workspaceId, userId }, identity, models);
  if (changes.notificationPreferences) await models.AmbassadorProfile.updateOne({ workspaceId, userId, status: "active" }, { $set: { "notificationPreferences.email": changes.notificationPreferences.email !== false, "notificationPreferences.inApp": changes.notificationPreferences.inApp !== false } });
  return ownProfileWithCompleteness({ workspaceId, userId }, models);
}
async function referrals({ workspaceId, ambassadorProfileId }, models = deps) { return models.ReferralAttribution.find({ workspaceId, ambassadorProfileId, promoterType: "ambassador" }).populate("contactId", "name firstName lastName email status").populate("applicationId", "status submittedAt coachingProgramId").populate("enrollmentId", "status startsAt coachingProgramId").sort({ attributedAt: -1 }).lean(); }
async function payouts({ workspaceId, ambassadorProfileId }, models = deps) { return models.CommissionLedger.find({ workspaceId, ambassadorProfileId, beneficiaryType: "ambassador" }).populate("contactId", "name firstName lastName email").populate("coachingProgramId", "name").sort({ calculatedAt: -1 }).lean(); }
async function updateProfile({ workspaceId, profileId, changes }, models = deps) { const update = {}; for (const key of ["displayName", "communityUrl", "notes", "startDate", "contactId"]) if (changes[key] !== undefined) update[key] = changes[key]; if (changes.commissionConfig) update.commissionConfig = changes.commissionConfig; const profile = await models.AmbassadorProfile.findOneAndUpdate({ _id: profileId, workspaceId }, { $set: update }, { new: true, runValidators: true }); if (!profile) throw fail("Ambassador profile not found", "AMBASSADOR_NOT_FOUND"); return profile; }
async function setStatus({ workspaceId, profileId, status }, models = deps) { if (!["active", "inactive"].includes(status)) throw fail("Valid ambassador status required", "AMBASSADOR_STATUS_INVALID"); const profile = await models.AmbassadorProfile.findOneAndUpdate({ _id: profileId, workspaceId }, { $set: { status, deactivatedAt: status === "inactive" ? new Date() : null } }, { new: true }); if (!profile) throw fail("Ambassador profile not found", "AMBASSADOR_NOT_FOUND"); return profile; }
async function transitionReferral({ workspaceId, attributionId, state, actorUserId }, models = deps) { const allowed = ["referred", "applied", "qualified", "enrolled", "converted", "cancelled", "refunded"]; if (!allowed.includes(state)) throw fail("Invalid referral state", "REFERRAL_STATE_INVALID"); const row = await models.ReferralAttribution.findOne({ _id: attributionId, workspaceId, promoterType: "ambassador" }); if (!row) throw fail("Ambassador referral not found", "REFERRAL_NOT_FOUND"); row.state = state; await row.save(); await models.CrmActivity.create({ workspaceId, contactId: row.contactId, type: "system", source: "crm", title: `Ambassador referral marked ${state}`, createdBy: actorUserId, metadata: { eventType: "ambassador.referral.state_changed", referralAttributionId: row._id, state } }); return row; }
async function createPayout(input, models = deps) {
  const attribution = await models.ReferralAttribution.findOne({ _id: input.referralAttributionId, workspaceId: input.workspaceId, promoterType: "ambassador" }).lean(); if (!attribution) throw fail("Ambassador referral not found", "REFERRAL_NOT_FOUND");
  const profile = await models.AmbassadorProfile.findOne({ _id: attribution.ambassadorProfileId, workspaceId: input.workspaceId }).lean(); if (!profile) throw fail("Ambassador profile not found", "AMBASSADOR_NOT_FOUND");
  let enrollment = null; if (input.enrollmentId) { enrollment = await models.Enrollment.findOne({ _id: input.enrollmentId, workspaceId: input.workspaceId, contactId: attribution.contactId }).lean(); if (!enrollment) throw fail("Enrollment must belong to the referred Contact and workspace", "ENROLLMENT_MISMATCH"); }
  const gross = Math.max(0, Math.round(Number(input.grossAmountMinor) || 0)), config = profile.commissionConfig || { mode: "manual" };
  const amount = config.mode === "percent" ? Math.round(gross * (Number(config.rateBps) || 0) / 10000) : config.mode === "fixed" ? Number(config.fixedAmountMinor) || 0 : Math.max(0, Math.round(Number(input.commissionAmountMinor) || 0));
  const saleReference = String(input.saleReference || `ambassador:${attribution._id}:${enrollment?._id || "manual"}`);
  const existing = await models.CommissionLedger.findOne({ workspaceId: input.workspaceId, saleType: "manual", saleReference }); if (existing) return existing;
  const row = await models.CommissionLedger.create({ workspaceId: input.workspaceId, referralAttributionId: attribution._id, beneficiaryType: "ambassador", ambassadorProfileId: profile._id, ambassadorUserId: profile.userId, contactId: attribution.contactId, coachingProgramId: enrollment?.coachingProgramId || null, productLabel: input.productLabel || enrollment?.programSnapshot?.name || "Ambassador referral", saleType: "manual", saleReference, grossAmountMinor: gross, rateBps: config.mode === "percent" ? config.rateBps : 0, commissionAmountMinor: amount, currency: config.currency || input.currency || "USD", status: "pending", calculatedAt: new Date(), ruleSnapshot: { source: "ambassador_profile", mode: config.mode, rateBps: config.rateBps || 0, fixedAmountMinor: config.fixedAmountMinor || 0 }, payoutNotes: String(input.notes || "").trim(), createdBy: input.actorUserId });
  await models.CrmActivity.create({ workspaceId: input.workspaceId, contactId: attribution.contactId, type: "system", source: "crm", title: "Ambassador payout created", createdBy: input.actorUserId, metadata: { eventType: "ambassador.payout.created", commissionLedgerId: row._id, ambassadorProfileId: profile._id, commissionAmountMinor: amount } }); return row;
}
async function transitionPayout({ workspaceId, payoutId, status, notes = "", actorUserId }, models = deps) { const row = await models.CommissionLedger.findOne({ _id: payoutId, workspaceId, beneficiaryType: "ambassador" }); if (!row) throw fail("Ambassador payout not found", "PAYOUT_NOT_FOUND"); const allowed = { pending: ["approved", "void"], approved: ["paid", "void"], paid: ["void"], void: [] }; if (!allowed[row.status]?.includes(status)) throw fail("Invalid payout status transition", "PAYOUT_STATUS_INVALID"); row.status = status; row.updatedBy = actorUserId; row.payoutNotes = String(notes || row.payoutNotes || "").trim(); if (status === "approved") row.approvedAt = new Date(); if (status === "paid") row.paidAt = new Date(); if (status === "void") { row.reversedAt = new Date(); row.reversalReason = row.payoutNotes || "Voided by administrator"; } await row.save(); await models.CrmActivity.create({ workspaceId, contactId: row.contactId, type: "system", source: "crm", title: `Ambassador payout ${status}`, createdBy: actorUserId, metadata: { eventType: `ambassador.payout.${status}`, commissionLedgerId: row._id, notes: row.payoutNotes } }); return row; }
module.exports = { createPayout, ownProfile, ownProfileWithCompleteness, payouts, referralUrl, referrals, setStatus, transitionPayout, transitionReferral, updateOwnProfile, updateProfile };
