const templates = Object.freeze([
  { key: "application_completed", name: "Application completed", description: "Confirm the application, notify the closer, and create follow-up.", trigger: { eventType: "application.completed" }, conditions: [], actions: [{ type: "contact.add_tag", config: { tag: "application-completed" } }, { type: "communication.email", config: { purpose: "transactional", subject: "We received your application", body: "Hi {{contact.firstName}}, we received your application and will be in touch." } }, { type: "communication.sms", config: { purpose: "transactional", body: "We received your Ellie Coaching application. We will be in touch soon." } }, { type: "notification.create", config: { role: "closer", title: "New coaching application" } }, { type: "task.create", config: { title: "Follow up on coaching application", dueMinutes: 1440 } }] },
  { key: "call_booked", name: "Call booked", description: "Send confirmations and create configurable reminder jobs.", trigger: { eventType: "coaching.session.scheduled" }, conditions: [], actions: [{ type: "communication.email", config: { purpose: "transactional", subject: "Your call is booked", body: "Your call is confirmed. Check your calendar for the meeting details." } }, { type: "communication.sms", config: { purpose: "transactional", body: "Your call is booked. Check your calendar for details." } }, { type: "communication.session_reminders", config: { offsetsMinutes: [1440, 60], channels: ["email", "sms"] } }] },
  { key: "closed_won", name: "Closed won onboarding", description: "Create enrollment, commission, access, and welcome steps after a sale.", trigger: { eventType: "opportunity.closed_won" }, conditions: [], actions: [{ type: "enrollment.create", config: { coachingProgramId: "", status: "active" } }, { type: "commission.generate", config: {} }, { type: "skool.request_access", config: {} }, { type: "communication.onboarding", config: { channels: ["email", "sms"] } }] },
  { key: "coach_assignment", name: "Coach assignment notification", description: "Notify the assigned coach when a student becomes visible in Coach Portal.", trigger: { eventType: "coach.assigned" }, conditions: [], actions: [{ type: "notification.create", config: { role: "coach", title: "New student assignment" } }] },
  { key: "coach_handoff", name: "Coach handoff notification", description: "Notify the incoming coach after preserved handoff completion.", trigger: { eventType: "coaching.handoff.completed" }, conditions: [], actions: [{ type: "notification.create", config: { role: "coach", title: "Student handoff completed" } }] },
  { key: "social_lead", name: "Social lead follow-up", description: "Tag a social lead, create a tracked application CTA, and follow up only if still needed.", trigger: { eventType: "social.lead.created" }, conditions: [], actions: [{ type: "contact.add_tag", config: { tag: "social-lead" } }, { type: "social.tracked_link", config: { destination: "https://elliescoaching.com/apply" } }, { type: "task.create", delayMinutes: 1440, conditions: [{ field: "contact.applicationCompleted", operator: "equals", value: false }], config: { title: "Review social lead application status" } }] },
  { key: "eventbrite_lead", name: "Eventbrite registration nurture", description: "Tag registrants and schedule consent-aware event follow-up.", trigger: { eventType: "event.registered" }, conditions: [], actions: [{ type: "contact.add_tag", config: { tag: "eventbrite-registrant" } }, { type: "communication.email", config: { purpose: "transactional", subject: "Registration confirmed", body: "Your registration is confirmed. We look forward to seeing you." } }] },
  { key: "session_reminders", name: "Coaching session reminders", description: "Create editable 24-hour and 1-hour reminders using the existing stale-job safeguards.", trigger: { eventType: "coaching.session.scheduled" }, conditions: [], actions: [{ type: "communication.session_reminders", config: { offsetsMinutes: [1440, 60], channels: ["email"] } }] },
]);
module.exports = { templates };
