const InvitationTemplate = require("../models/InvitationTemplate");
const Workspace = require("../models/Workspace");
const User = require("../models/User");
const defaults = Object.freeze({
  coach: { subject: "You’re invited to coach with {{workspaceName}}", body: "Hi {{firstName}},\n\n{{invitedBy}} invited you to join {{workspaceName}} as a Coach. Use the secure link below to create your account and access only your assigned coaching workspace.\n\n{{inviteLink}}\n\nWelcome to the team." },
  ambassador: { subject: "You’re invited to become a Brand Ambassador for {{workspaceName}}", body: "Hi {{firstName}},\n\n{{invitedBy}} invited you to join {{workspaceName}} as a Brand Ambassador. Activate your account to access your referral link, referral status, and payout history.\n\n{{inviteLink}}" },
  closer: { subject: "You’re invited to the {{workspaceName}} sales team", body: "Hi {{firstName}},\n\n{{invitedBy}} invited you to join {{workspaceName}} as a Closer / Sales team member. Activate your account to access only the sales records assigned to you.\n\n{{inviteLink}}" },
  general: { subject: "You’re invited to join {{workspaceName}}", body: "Hi {{firstName}},\n\n{{invitedBy}} invited you to join {{workspaceName}} as {{role}}. Create your account using this secure invitation link:\n\n{{inviteLink}}" },
});
function roleKey(roles = []) { return roles.includes("coach") ? "coach" : roles.includes("ambassador") ? "ambassador" : roles.includes("closer") ? "closer" : "general"; }
function substitute(value, variables) { return String(value || "").replace(/{{(firstName|displayName|role|workspaceName|inviteLink|invitedBy)}}/g, (_match, key) => String(variables[key] || "")); }
async function list(workspaceId) { const saved = await InvitationTemplate.find({ workspaceId }).lean(); const map = new Map(saved.map((row) => [row.roleKey, row])); return Object.entries(defaults).map(([key, value]) => ({ roleKey: key, ...(map.get(key) || { ...value, version: 1, customized: false }), customized: Boolean(map.get(key)) })); }
async function get(workspaceId, key) { const saved = await InvitationTemplate.findOne({ workspaceId, roleKey: key }).lean(); return saved || { roleKey: key, ...defaults[key], version: 1, customized: false }; }
async function save({ workspaceId, roleKey: key, subject, body, actorUserId }) { if (!defaults[key]) throw new Error("Valid invitation role template required"); if (!String(subject || "").trim() || !String(body || "").trim()) throw new Error("Invitation subject and message are required"); const current = await InvitationTemplate.findOne({ workspaceId, roleKey: key }).lean(); return InvitationTemplate.findOneAndUpdate({ workspaceId, roleKey: key }, { $set: { subject: String(subject).trim(), body: String(body), version: (current?.version || 0) + 1, updatedBy: actorUserId } }, { upsert: true, new: true, setDefaultsOnInsert: true }); }
async function reset({ workspaceId, roleKey: key }) { if (!defaults[key]) throw new Error("Valid invitation role template required"); await InvitationTemplate.deleteOne({ workspaceId, roleKey: key }); return { roleKey: key, ...defaults[key], version: 1, customized: false }; }
async function variables({ workspaceId, name, roles, inviteLink, invitedByUserId }) { const [workspace, inviter] = await Promise.all([Workspace.findById(workspaceId).select("name").lean(), User.findById(invitedByUserId).select("name").lean()]); return { firstName: String(name || "").trim().split(/\s+/)[0], displayName: name, role: roleKey(roles) === "general" ? (roles[0] || "Team Member") : ({ coach: "Coach", ambassador: "Brand Ambassador", closer: "Closer / Sales" })[roleKey(roles)], workspaceName: workspace?.name || "Growth Operator", inviteLink, invitedBy: inviter?.name || "A workspace administrator" }; }
function render(template, vars) { return { subject: substitute(template.subject, vars), body: substitute(template.body, vars) }; }
module.exports = { defaults, get, list, render, reset, roleKey, save, variables };
