const crypto = require("crypto");
const axios = require("axios");
const IntegrationConnection = require("../models/IntegrationConnection");
const MeetupActionRequest = require("../models/MeetupActionRequest");
const CrmActivity = require("../models/CrmActivity");
const Contact = require("../models/Contact");
const { encryptCredentials, decryptCredentials } = require("../utils/credentialEncryption");
const PROVIDER = "meetup";
const AUTHORIZE_URL = "https://secure.meetup.com/oauth2/authorize";
const TOKEN_URL = "https://secure.meetup.com/oauth2/access";
const GRAPHQL_URL = "https://api.meetup.com/gql-ext";
const deps = { IntegrationConnection, MeetupActionRequest, CrmActivity, Contact };
function safeError(error) { return String(error?.response?.data?.errors?.[0]?.message || error?.message || "Meetup request failed").slice(0, 500); }
function config() { const clientId = String(process.env.MEETUP_CLIENT_ID || "").trim(); const clientSecret = String(process.env.MEETUP_CLIENT_SECRET || "").trim(); const redirectUri = String(process.env.MEETUP_REDIRECT_URI || "").trim(); if (!clientId || !clientSecret || !redirectUri) throw new Error("Meetup OAuth is not configured"); return { clientId, clientSecret, redirectUri }; }
function stateKey() { return Buffer.from(String(process.env.INTEGRATION_CREDENTIAL_ENCRYPTION_KEY || ""), "base64"); }
function createState(workspaceId, userId) { const key = stateKey(); if (key.length !== 32 || !workspaceId || !userId) throw new Error("Meetup OAuth state cannot be created"); const body = Buffer.from(JSON.stringify({ workspaceId: String(workspaceId), userId: String(userId), nonce: crypto.randomBytes(18).toString("hex"), expiresAt: Date.now() + 600000 })).toString("base64url"); return `${body}.${crypto.createHmac("sha256", key).update(body).digest("base64url")}`; }
function verifyState(value) { try { const [body, signature] = String(value || "").split("."); const key = stateKey(); const expected = crypto.createHmac("sha256", key).update(body).digest(); const supplied = Buffer.from(signature, "base64url"); if (key.length !== 32 || supplied.length !== expected.length || !crypto.timingSafeEqual(supplied, expected)) return null; const state = JSON.parse(Buffer.from(body, "base64url").toString()); return state.expiresAt > Date.now() ? state : null; } catch { return null; } }
function authorizationUrl(workspaceId, userId) { const value = config(); const url = new URL(AUTHORIZE_URL); url.searchParams.set("client_id", value.clientId); url.searchParams.set("response_type", "code"); url.searchParams.set("redirect_uri", value.redirectUri); url.searchParams.set("state", createState(workspaceId, userId)); return url.toString(); }
async function graphql(accessToken, query, variables = {}, client = axios) { const response = await client.post(GRAPHQL_URL, { query, variables }, { headers: { Authorization: `Bearer ${accessToken}`, "Content-Type": "application/json" } }); if (response.data?.errors?.length) throw new Error(response.data.errors[0].message || "Meetup GraphQL request failed"); return response.data?.data || {}; }
async function exchangeCode(code, models = deps, client = axios) { const value = config(); const body = new URLSearchParams({ client_id: value.clientId, client_secret: value.clientSecret, grant_type: "authorization_code", redirect_uri: value.redirectUri, code }); const response = await client.post(TOKEN_URL, body.toString(), { headers: { "Content-Type": "application/x-www-form-urlencoded" } }); const tokens = response.data || {}; if (!tokens.access_token) throw new Error("Meetup did not return an access token"); const profile = (await graphql(tokens.access_token, "query { self { id name } }", {}, client)).self || {}; return publicStatus(await models.IntegrationConnection.findOneAndUpdate({ provider: PROVIDER, accountScope: "workspace" }, { $set: { provider: PROVIDER, accountScope: "workspace", status: "connected", credentialsEncrypted: encryptCredentials({ accessToken: tokens.access_token, refreshToken: tokens.refresh_token || "" }), settings: { accountName: profile.name || "Meetup account", proNetworkUrlname: "", selectedGroupUrlnames: [] }, "oauth.providerAccountId": String(profile.id || ""), "oauth.expiresAt": tokens.expires_in ? new Date(Date.now() + Number(tokens.expires_in) * 1000) : null, connectedAt: new Date(), lastVerifiedAt: new Date(), lastError: null }, $unset: { credentials: 1 } }, { upsert: true, new: true, setDefaultsOnInsert: true })); }
async function connection(models = deps) { return models.IntegrationConnection.findOne({ provider: PROVIDER, accountScope: "workspace" }).select("+credentialsEncrypted"); }
async function accessToken(row, models = deps, client = axios) { const credentials = decryptCredentials(row.credentialsEncrypted); if (!row.oauth?.expiresAt || new Date(row.oauth.expiresAt).getTime() > Date.now() + 60000) return credentials.accessToken; if (!credentials.refreshToken) throw new Error("Reconnect Meetup to renew authorization"); const value = config(); const body = new URLSearchParams({ client_id: value.clientId, client_secret: value.clientSecret, grant_type: "refresh_token", refresh_token: credentials.refreshToken }); const response = await client.post(TOKEN_URL, body.toString(), { headers: { "Content-Type": "application/x-www-form-urlencoded" } }); const tokens = response.data || {}; if (!tokens.access_token || !tokens.refresh_token) throw new Error("Meetup token refresh did not return rotating credentials"); row.credentialsEncrypted = encryptCredentials({ accessToken: tokens.access_token, refreshToken: tokens.refresh_token }); row.oauth.expiresAt = tokens.expires_in ? new Date(Date.now() + Number(tokens.expires_in) * 1000) : null; row.lastVerifiedAt = new Date(); await row.save(); return tokens.access_token; }
function publicStatus(row) { return { configured: Boolean(process.env.MEETUP_CLIENT_ID && process.env.MEETUP_CLIENT_SECRET && process.env.MEETUP_REDIRECT_URI && process.env.INTEGRATION_CREDENTIAL_ENCRYPTION_KEY), connected: row?.status === "connected", status: row?.status || "disconnected", accountName: row?.settings?.accountName || "", providerAccountId: row?.oauth?.providerAccountId || "", proNetworkUrlname: row?.settings?.proNetworkUrlname || "", selectedGroupUrlnames: row?.settings?.selectedGroupUrlnames || [], connectedAt: row?.connectedAt || null, lastVerifiedAt: row?.lastVerifiedAt || null, lastError: row?.lastError || null, outboundEnabled: process.env.MEETUP_OUTBOUND_ENABLED === "true" }; }
async function status(models = deps) { return publicStatus(await models.IntegrationConnection.findOne({ provider: PROVIDER, accountScope: "workspace" })); }
async function assets(networkUrlname, models = deps, client = axios) { const row = await connection(models); if (!row) throw new Error("Connect Meetup first"); const token = await accessToken(row, models, client); const urlname = String(networkUrlname || row.settings?.proNetworkUrlname || "").trim(); if (!urlname) return { network: null, groups: [], events: [] }; const data = await graphql(token, `query($urlname: ID!) { proNetwork(urlname: $urlname) { groupsSearch(input: { first: 100, filter: {} }) { totalCount edges { node { id name urlname memberships { totalCount } } } } eventsSearch(input: { first: 50, filter: { status: "UPCOMING" } }) { totalCount edges { node { id title eventUrl dateTime group { id name urlname } } } } } }`, { urlname }, client); if (!data.proNetwork) throw new Error("That Meetup Pro network is not available to this authorization"); row.settings = { ...(row.settings || {}), proNetworkUrlname: urlname }; row.lastVerifiedAt = new Date(); row.lastError = null; await row.save(); return { network: { urlname }, groups: (data.proNetwork.groupsSearch?.edges || []).map(({ node }) => node), events: (data.proNetwork.eventsSearch?.edges || []).map(({ node }) => node) }; }
async function eventRsvps(eventId, models = deps, client = axios) { const row = await connection(models); if (!row) throw new Error("Connect Meetup first"); const token = await accessToken(row, models, client); const data = await graphql(token, `query($eventId: ID!) { event(id: $eventId) { id title group { id name urlname } rsvps { edges { node { id member { id name email } } } } } }`, { eventId: String(eventId) }, client); const event = data.event; if (!event) throw new Error("Meetup event not found or not authorized"); return { id: event.id, title: event.title, group: event.group, rsvps: (event.rsvps?.edges || []).map(({ node }) => ({ id: node.id, memberId: node.member?.id || "", name: node.member?.name || "", email: node.member?.email || "", emailAvailable: Boolean(node.member?.email) })) }; }
async function syncEventRsvps(eventId, workspaceId, actorUserId, models = deps, client = axios) { const event = await eventRsvps(eventId, models, client); let created = 0; let updated = 0; let unavailable = 0; for (const rsvp of event.rsvps) { const email = String(rsvp.email || "").trim().toLowerCase(); if (!email) { unavailable += 1; continue; } const existing = await models.Contact.findOne({ workspaceId, email }).select("_id").lean(); let contact; try { contact = await models.Contact.findOneAndUpdate({ workspaceId, email }, { $setOnInsert: { workspaceId, email, name: rsvp.name || "Meetup attendee", sourceProvider: "meetup", providerContactId: rsvp.memberId || undefined }, $addToSet: { sources: "meetup" }, $set: { "externalIds.meetup": rsvp.memberId || "" } }, { upsert: true, new: true, setDefaultsOnInsert: true }); } catch (error) { if (error.code !== 11000) throw error; contact = await models.Contact.findOne({ workspaceId, email }); } if (existing) updated += 1; else created += 1; await models.CrmActivity.findOneAndUpdate({ workspaceId, contactId: contact._id, "metadata.idempotencyKey": `meetup:rsvp:${event.id}:${rsvp.id}` }, { $setOnInsert: { workspaceId, contactId: contact._id, type: "system", title: "Meetup RSVP synchronized", source: "integration", createdBy: actorUserId, metadata: { eventType: "event.registered", provider: "meetup", providerEventId: event.id, providerRsvpId: rsvp.id, idempotencyKey: `meetup:rsvp:${event.id}:${rsvp.id}` } } }, { upsert: true, new: true }); } return { event: { id: event.id, title: event.title }, total: event.rsvps.length, created, updated, unavailable, note: "Only Meetup-returned attendee emails were synchronized; no marketing consent was inferred." }; }
async function selectGroups(groupUrlnames, models = deps) { const row = await connection(models); if (!row) throw new Error("Connect Meetup first"); row.settings = { ...(row.settings || {}), selectedGroupUrlnames: [...new Set((groupUrlnames || []).map(String))].slice(0, 100) }; await row.save(); return publicStatus(row); }
async function requestAction(input, models = deps) { const row = await models.IntegrationConnection.findOne({ provider: PROVIDER, accountScope: "workspace", status: "connected" }); if (!row) throw new Error("Connect Meetup before requesting an action"); const request = await models.MeetupActionRequest.findOneAndUpdate({ workspaceId: input.workspaceId, idempotencyKey: input.idempotencyKey }, { $setOnInsert: { workspaceId: input.workspaceId, connectionId: row._id, contactId: input.contactId || null, automationId: input.automationId || null, automationExecutionId: input.automationExecutionId || null, action: input.action, payload: input.payload, requestedBy: input.requestedBy || null, status: "pending_approval" } }, { upsert: true, new: true, setDefaultsOnInsert: true }); await models.CrmActivity.findOneAndUpdate({ workspaceId: input.workspaceId, "metadata.idempotencyKey": `${input.idempotencyKey}:activity` }, { $setOnInsert: { workspaceId: input.workspaceId, contactId: input.contactId || null, type: "task", title: "Meetup action requires approval", body: `${input.action.replaceAll("_", " ")} will not run until an Owner or Admin approves it.`, source: "integration", metadata: { eventType: "meetup.action.approval_requested", meetupActionRequestId: request._id, idempotencyKey: `${input.idempotencyKey}:activity` } } }, { upsert: true, new: true }); return request; }
async function executeApproved(id, actorUserId, models = deps, client = axios) { const request = await models.MeetupActionRequest.findOne({ _id: id }); if (!request) throw new Error("Meetup action request not found"); if (request.status === "completed") return request; if (request.status !== "pending_approval") throw new Error("Only pending Meetup actions can be approved"); request.approvedBy = actorUserId; request.approvedAt = new Date(); request.status = "approved"; await request.save(); if (process.env.MEETUP_OUTBOUND_ENABLED !== "true") return request; const row = await connection(models); const token = await accessToken(row, models, client); let operation; if (request.action === "create_event") operation = { query: "mutation($input: CreateEventInput!) { createEvent(input: $input) { event { id eventUrl } errors { message code field } } }", field: "createEvent" }; else if (request.action === "update_event") operation = { query: "mutation($input: EditEventInput!) { editEvent(input: $input) { event { id eventUrl } errors { message code field } } }", field: "editEvent" }; else throw new Error("Meetup event announcements require connected-schema confirmation before execution"); try { const data = await graphql(token, operation.query, { input: request.payload }, client); const result = data[operation.field]; if (result?.errors?.length) throw new Error(result.errors[0].message); request.status = "completed"; request.providerResult = { eventId: result?.event?.id || "", eventUrl: result?.event?.eventUrl || "" }; request.lastError = ""; await request.save(); await models.CrmActivity.create({ workspaceId: request.workspaceId, contactId: request.contactId, type: "system", direction: "outbound", title: `Meetup ${request.action.replaceAll("_", " ")} completed`, source: "integration", createdBy: actorUserId, metadata: { eventType: "meetup.action.completed", meetupActionRequestId: request._id, providerEventId: request.providerResult.eventId } }); return request; } catch (error) { request.status = "failed"; request.lastError = safeError(error); await request.save(); throw error; } }
async function rejectAction(id, actorUserId, reason, models = deps) { const request = await models.MeetupActionRequest.findOne({ _id: id, status: "pending_approval" }); if (!request) throw new Error("Pending Meetup action request not found"); request.status = "rejected"; request.rejectedBy = actorUserId; request.rejectedAt = new Date(); request.lastError = String(reason || "Rejected by Owner/Admin").slice(0, 1000); await request.save(); return request; }
async function disconnect(models = deps) { await models.IntegrationConnection.findOneAndUpdate({ provider: PROVIDER, accountScope: "workspace" }, { $set: { status: "disconnected", settings: {}, connectedAt: null, lastVerifiedAt: null, "oauth.providerAccountId": "", "oauth.expiresAt": null }, $unset: { credentials: 1, credentialsEncrypted: 1 } }); return status(models); }
module.exports = { GRAPHQL_URL, authorizationUrl, verifyState, exchangeCode, status, assets, eventRsvps, syncEventRsvps, selectGroups, requestAction, executeApproved, rejectAction, disconnect, graphql, accessToken, publicStatus, safeError, _deps: deps };
