const CoachProfile = require("../models/CoachProfile"); const ReferralAttribution = require("../models/ReferralAttribution"); const CommissionRule = require("../models/CommissionRule"); const CommissionLedger = require("../models/CommissionLedger");
const Contact = require("../models/Contact"); const Enrollment = require("../models/Enrollment"); const CrmActivity = require("../models/CrmActivity");
const deps = { CoachProfile, ReferralAttribution, CommissionRule, CommissionLedger, Contact, Enrollment, CrmActivity };
function err(message, code) { const error = new Error(message); error.code = code; return error; }
function code(value) { return String(value || "").trim().toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 80); }
async function event(models, value) { return models.CrmActivity.create({ ...value, type: "system", source: "crm" }); }

async function setReferralIdentity({ workspaceId, coachProfileId, referralCode, referralSlug, actorUserId }, models = deps) {
  const coach = await models.CoachProfile.findOne({ _id: coachProfileId, workspaceId }); if (!coach) throw err("Coach not found", "COACH_NOT_FOUND");
  const normalizedCode = code(referralCode); const slug = code(referralSlug || referralCode); if (normalizedCode.length < 3 || slug.length < 3) throw err("Referral code and slug must be at least three characters", "REFERRAL_CODE_INVALID");
  const duplicate = await models.CoachProfile.findOne({ workspaceId, _id: { $ne: coach._id }, $or: [{ referralCode: normalizedCode }, { referralSlug: slug }] }).lean(); if (duplicate) throw err("Referral code or slug is already in use", "REFERRAL_CODE_CONFLICT");
  coach.referralCode = normalizedCode; coach.referralSlug = slug; coach.updatedBy = actorUserId; await coach.save(); return coach;
}
async function resolveCoachByCode({ workspaceId, referralCode }, models = deps) { const normalized = code(referralCode); if (!normalized) return null; return models.CoachProfile.findOne({ workspaceId, status: "active", $or: [{ referralCode: normalized }, { referralSlug: normalized }] }).lean(); }
async function attributeReferral({ workspaceId, contactId, referralCode, source = "manual", actorUserId = null, correct = false, correctionReason = "" }, models = deps) {
  const [contact, coach] = await Promise.all([models.Contact.findOne({ _id: contactId, workspaceId }).lean(), resolveCoachByCode({ workspaceId, referralCode }, models)]); if (!contact) throw err("Contact not found", "CONTACT_NOT_FOUND"); if (!coach) throw err("Valid active coach referral code required", "REFERRAL_CODE_INVALID");
  let existing = await models.ReferralAttribution.findOne({ workspaceId, contactId });
  if (existing && !correct) return existing;
  if (existing) { if (!correctionReason.trim()) throw err("Correction reason is required", "CORRECTION_REASON_REQUIRED"); const previous = existing.coachProfileId; existing.previousCoachProfileId = previous; existing.coachProfileId = coach._id; existing.coachUserId = coach.userId; existing.referralCode = coach.referralCode; existing.source = source; existing.correctedAt = new Date(); existing.correctionReason = correctionReason.trim(); existing.correctedBy = actorUserId; await existing.save(); await event(models, { workspaceId, contactId, title: "Coach referral corrected", createdBy: actorUserId, metadata: { eventType: "coaching.referral.corrected", referralAttributionId: existing._id, previousCoachProfileId: previous, coachProfileId: coach._id, reason: correctionReason.trim() } }); return existing; }
  const created = await models.ReferralAttribution.create({ workspaceId, contactId, coachProfileId: coach._id, coachUserId: coach.userId, referralCode: coach.referralCode, source, attributedAt: new Date(), createdBy: actorUserId }); await event(models, { workspaceId, contactId, title: "Coach referral attributed", createdBy: actorUserId, metadata: { eventType: "coaching.referral.attributed", referralAttributionId: created._id, coachProfileId: coach._id, referralCode: coach.referralCode } }); return created;
}
function validateRule(input) { const rateBps = Math.round(Number(input.rateBps)); if (!Number.isInteger(rateBps) || rateBps < 0 || rateBps > 10000) throw err("Commission rate must be between 0% and 100%", "COMMISSION_RATE_INVALID"); if (input.scope === "coach" && !input.coachProfileId) throw err("Coach rule requires a coach", "COMMISSION_RULE_INVALID"); if (input.scope === "program" && !input.coachingProgramId) throw err("Program rule requires a program", "COMMISSION_RULE_INVALID"); if (input.scope === "product" && !code(input.productKey)) throw err("Product rule requires a product key", "COMMISSION_RULE_INVALID"); return rateBps; }
async function saveRule(input, models = deps) { const rateBps = validateRule(input); if (input.coachProfileId && !await models.CoachProfile.exists({ _id: input.coachProfileId, workspaceId: input.workspaceId })) throw err("Coach must belong to workspace", "COACH_WORKSPACE_MISMATCH"); const key = { workspaceId: input.workspaceId, scope: input.scope, coachProfileId: input.coachProfileId || null, coachingProgramId: input.coachingProgramId || null, productKey: code(input.productKey) }; return models.CommissionRule.findOneAndUpdate(key, { $set: { label: String(input.label || "Commission rule").trim(), rateBps, active: input.active !== false, updatedBy: input.actorUserId }, $setOnInsert: { createdBy: input.actorUserId } }, { upsert: true, new: true, setDefaultsOnInsert: true }); }
async function resolveRule({ workspaceId, coachProfileId, coachingProgramId = null, productKey = "" }, models = deps) { const rules = await models.CommissionRule.find({ workspaceId, active: true, $or: [{ scope: "product", productKey: code(productKey) }, { scope: "program", coachingProgramId }, { scope: "coach", coachProfileId }, { scope: "default" }] }).lean(); const order = { product: 4, program: 3, coach: 2, default: 1 }; return rules.filter((r) => r.scope !== "product" || r.productKey === code(productKey)).filter((r) => r.scope !== "program" || String(r.coachingProgramId) === String(coachingProgramId)).sort((a,b) => order[b.scope]-order[a.scope])[0] || null; }
async function generateCommission(input, models = deps) { const existing = await models.CommissionLedger.findOne({ workspaceId: input.workspaceId, saleType: input.saleType, saleReference: String(input.saleReference) }); if (existing) return existing; const attribution = await models.ReferralAttribution.findOne({ workspaceId: input.workspaceId, contactId: input.contactId }).lean(); if (!attribution) return null; const rule = await resolveRule({ workspaceId: input.workspaceId, coachProfileId: attribution.coachProfileId, coachingProgramId: input.coachingProgramId, productKey: input.productKey }, models); if (!rule) return null; const gross = Math.max(0, Math.round(Number(input.grossAmountMinor) || 0)); const amount = Math.round(gross * rule.rateBps / 10000); try { const row = await models.CommissionLedger.create({ workspaceId: input.workspaceId, referralAttributionId: attribution._id, coachProfileId: attribution.coachProfileId, coachUserId: attribution.coachUserId, contactId: input.contactId, coachingProgramId: input.coachingProgramId || null, productKey: code(input.productKey), productLabel: input.productLabel || "", saleType: input.saleType, saleReference: String(input.saleReference), grossAmountMinor: gross, rateBps: rule.rateBps, commissionAmountMinor: amount, currency: input.currency || "USD", status: "pending", calculatedAt: new Date(), ruleSnapshot: { ruleId: rule._id, scope: rule.scope, label: rule.label, rateBps: rule.rateBps }, createdBy: input.actorUserId || null }); await event(models, { workspaceId: input.workspaceId, contactId: input.contactId, title: "Coach commission created", createdBy: input.actorUserId, metadata: { eventType: "coaching.commission.created", commissionLedgerId: row._id, coachProfileId: attribution.coachProfileId, grossAmountMinor: gross, commissionAmountMinor: amount, currency: row.currency } }); return row; } catch (error) { if (error.code === 11000) return models.CommissionLedger.findOne({ workspaceId: input.workspaceId, saleType: input.saleType, saleReference: String(input.saleReference) }); throw error; } }
async function generateFromOpportunity({ workspaceId, opportunity, actorUserId }, models = deps) { if (!opportunity?.primaryContactId || !opportunity?.wonAt) return null; const enrollment = await models.Enrollment.findOne({ workspaceId, sourceOpportunityId: opportunity._id }).lean(); return generateCommission({ workspaceId, contactId: opportunity.primaryContactId, coachingProgramId: enrollment?.coachingProgramId || null, productLabel: enrollment?.programSnapshot?.name || opportunity.name, saleType: "sales_opportunity", saleReference: opportunity._id, grossAmountMinor: Math.round((Number(opportunity.value) || 0) * 100), currency: opportunity.currency || "USD", actorUserId }, models); }
async function transitionCommission({ workspaceId, commissionId, status, reason = "", actorUserId }, models = deps) { const row = await models.CommissionLedger.findOne({ _id: commissionId, workspaceId }); if (!row) throw err("Commission not found", "COMMISSION_NOT_FOUND"); const allowed = { pending: ["approved","reversed"], approved: ["paid","reversed"], paid: ["reversed"], reversed: [] }; if (!allowed[row.status]?.includes(status)) throw err("Invalid commission status transition", "COMMISSION_STATUS_INVALID"); if (status === "reversed" && !reason.trim()) throw err("Reversal reason is required", "REVERSAL_REASON_REQUIRED"); row.status = status; row.updatedBy = actorUserId; if (status === "approved") row.approvedAt = new Date(); if (status === "paid") row.paidAt = new Date(); if (status === "reversed") { row.reversedAt = new Date(); row.reversalReason = reason.trim(); } await row.save(); await event(models, { workspaceId, contactId: row.contactId, title: `Coach commission ${status}`, createdBy: actorUserId, metadata: { eventType: `coaching.commission.${status}`, commissionLedgerId: row._id, reason: row.reversalReason } }); return row; }
module.exports = { attributeReferral, generateCommission, generateFromOpportunity, resolveCoachByCode, resolveRule, saveRule, setReferralIdentity, transitionCommission };
