const express = require("express");
const AmbassadorProfile = require("../models/AmbassadorProfile");
const service = require("../services/ambassadorService");
const workspaceMemberService = require("../services/workspaceMemberService");
const { requireCapability } = require("../middleware/auth");
const router = express.Router();
const admin = requireCapability("ambassadors.manage");
const asyncRoute = (handler) => (req, res, next) => Promise.resolve(handler(req, res, next)).catch(next);
const actorId = (req) => req.auth.user._id;
router.use(requireCapability("ambassadors.view_own", "ambassadors.view", "ambassadors.manage"));
router.get("/me", asyncRoute(async (req, res) => res.json({ success: true, data: await service.ownProfile({ workspaceId: req.auth.workspaceId, userId: actorId(req) }) })));
router.get("/me/referrals", asyncRoute(async (req, res) => { const profile = await service.ownProfile({ workspaceId: req.auth.workspaceId, userId: actorId(req) }); res.json({ success: true, data: await service.referrals({ workspaceId: req.auth.workspaceId, ambassadorProfileId: profile._id }) }); }));
router.get("/me/payouts", asyncRoute(async (req, res) => { const profile = await service.ownProfile({ workspaceId: req.auth.workspaceId, userId: actorId(req) }); res.json({ success: true, data: await service.payouts({ workspaceId: req.auth.workspaceId, ambassadorProfileId: profile._id }) }); }));
router.get("/", requireCapability("ambassadors.view", "ambassadors.manage"), asyncRoute(async (req, res) => res.json({ success: true, data: await AmbassadorProfile.find({ workspaceId: req.auth.workspaceId }).populate("userId", "name email lastLoginAt avatarUrl").sort({ displayName: 1 }).lean() })));
router.post("/", admin, asyncRoute(async (req, res) => { const data = await workspaceMemberService.onboardAmbassador({ ...req.body, workspaceId: req.auth.workspaceId, actorUserId: actorId(req) }); const lifecycle = data.membership.status === "active" ? "ambassador_profile_active" : "invite_ready"; res.status(data.alreadyActive ? 200 : 201).json({ success: true, data: { profile: data.ambassadorProfile, lifecycle, invitation: data.invitation ? { id: data.invitation._id, status: data.invitation.status, deliveryStatus: data.invitation.deliveryStatus, roleKey: data.invitation.roleKey, templateVersion: data.invitation.templateVersion, subject: data.invitation.subject, body: data.invitation.body, expiresAt: data.invitation.expiresAt } : null } }); }));
router.patch("/:id", admin, asyncRoute(async (req, res) => res.json({ success: true, data: await service.updateProfile({ workspaceId: req.auth.workspaceId, profileId: req.params.id, changes: req.body || {} }) })));
router.patch("/:id/status", admin, asyncRoute(async (req, res) => res.json({ success: true, data: await service.setStatus({ workspaceId: req.auth.workspaceId, profileId: req.params.id, status: req.body?.status }) })));
router.get("/:id/referrals", requireCapability("ambassadors.view", "ambassadors.manage"), asyncRoute(async (req, res) => res.json({ success: true, data: await service.referrals({ workspaceId: req.auth.workspaceId, ambassadorProfileId: req.params.id }) })));
router.patch("/referrals/:id/state", admin, asyncRoute(async (req, res) => res.json({ success: true, data: await service.transitionReferral({ workspaceId: req.auth.workspaceId, attributionId: req.params.id, state: req.body?.state, actorUserId: actorId(req) }) })));
router.get("/:id/payouts", requireCapability("ambassadors.view", "ambassadors.manage"), asyncRoute(async (req, res) => res.json({ success: true, data: await service.payouts({ workspaceId: req.auth.workspaceId, ambassadorProfileId: req.params.id }) })));
router.post("/payouts", admin, asyncRoute(async (req, res) => res.status(201).json({ success: true, data: await service.createPayout({ ...req.body, workspaceId: req.auth.workspaceId, actorUserId: actorId(req) }) })));
router.patch("/payouts/:id/status", admin, asyncRoute(async (req, res) => res.json({ success: true, data: await service.transitionPayout({ workspaceId: req.auth.workspaceId, payoutId: req.params.id, status: req.body?.status, notes: req.body?.notes, actorUserId: actorId(req) }) })));
module.exports = router;
