const express = require("express");
const Automation = require("../models/Automation");
const AutomationExecution = require("../models/AutomationExecution");
const CommunicationJob = require("../models/CommunicationJob");
const { requireCapability } = require("../middleware/auth");
const engine = require("../services/automationEngineService");
const { templates } = require("../services/automationTemplates");

const router = express.Router();
router.use(requireCapability("automations.manage"));
router.get("/catalog", (_req, res) => res.json({ success: true, data: { triggers: engine.TRIGGERS, conditionFields: engine.CONDITION_FIELDS, actions: engine.ACTIONS, templates } }));
router.get("/", async (_req, res) => res.json({ success: true, data: await Automation.find({ status: { $ne: "archived" } }).sort({ updatedAt: -1 }).lean() }));
router.post("/", async (req, res) => { try { const definition = engine.normalizeDefinition(req.body); const row = await Automation.create({ ...definition, status: req.body.status === "enabled" ? "enabled" : "draft", enabledAt: req.body.status === "enabled" ? new Date() : null, createdBy: req.auth.userId, updatedBy: req.auth.userId }); res.status(201).json({ success: true, data: row }); } catch (error) { res.status(400).json({ error: error.message, code: error.code }); } });
router.post("/from-template/:key", async (req, res) => { const template = templates.find((item) => item.key === req.params.key); if (!template) return res.status(404).json({ error: "Template not found" }); const definition = engine.normalizeDefinition({ ...template, ...req.body, templateKey: template.key, trigger: req.body.trigger || template.trigger, actions: req.body.actions || template.actions }); const row = await Automation.create({ ...definition, status: "draft", createdBy: req.auth.userId, updatedBy: req.auth.userId }); res.status(201).json({ success: true, data: row }); });
router.patch("/:id", async (req, res) => { try { const row = await Automation.findById(req.params.id); if (!row) return res.status(404).json({ error: "Automation not found" }); const definition = engine.normalizeDefinition({ ...row.toObject(), ...req.body, trigger: req.body.trigger || row.trigger, conditions: req.body.conditions || row.conditions, actions: req.body.actions || row.actions }); Object.assign(row, definition); row.updatedBy = req.auth.userId; await row.save(); res.json({ success: true, data: row }); } catch (error) { res.status(400).json({ error: error.message, code: error.code }); } });
router.patch("/:id/status", async (req, res) => { const status = req.body.status; if (!["enabled", "disabled", "archived"].includes(status)) return res.status(400).json({ error: "Invalid automation status" }); const row = await Automation.findById(req.params.id); if (!row) return res.status(404).json({ error: "Automation not found" }); row.status = status; row.updatedBy = req.auth.userId; if (status === "enabled") { row.enabledAt = new Date(); row.lastScannedAt = new Date(); } await row.save(); res.json({ success: true, data: row }); });
router.get("/executions/recent", async (req, res) => { const query = {}; if (req.query.automationId) query.automationId = req.query.automationId; if (req.query.status) query.status = req.query.status; const rows = await AutomationExecution.find(query).populate("automationId", "name trigger status").sort({ createdAt: -1 }).limit(Math.min(Number(req.query.limit) || 100, 250)).lean(); const jobIds = rows.flatMap((row) => row.steps || []).map((step) => step.result?.id).filter(Boolean); const jobs = await CommunicationJob.find({ _id: { $in: jobIds } }).select("status blockReason providerMessageId").lean(); const byId = new Map(jobs.map((job) => [String(job._id), job])); res.json({ success: true, data: rows.map((row) => ({ ...row, steps: (row.steps || []).map((step) => ({ ...step, communicationJob: byId.get(String(step.result?.id)) || null })) })) }); });
router.post("/executions/:id/retry", async (req, res) => { const row = await AutomationExecution.findById(req.params.id); if (!row) return res.status(404).json({ error: "Execution not found" }); if (!row.steps.some((step) => step.status === "failed") || row.attempts >= row.maxAttempts) return res.status(400).json({ error: "Execution is not safely retryable" }); row.status = "pending"; row.runAt = new Date(); row.lastError = ""; await row.save(); res.json({ success: true, data: row }); });
module.exports = router;
