import { useEffect, useState } from "react";
import { fetchAmbassadorContentTasks, fetchAmbassadorNotifications, updateAmbassadorContentTask } from "../services/api.js";
export default function AmbassadorContentTasks() {
  const [notifications, setNotifications] = useState([]);
  useEffect(() => { let active = true; fetchAmbassadorNotifications().then(rows => { if (active) setNotifications(rows); }).catch(() => {}); return () => { active = false; }; }, []);
  const [tasks, setTasks] = useState([]), [error, setError] = useState(""), [urls, setUrls] = useState({});
  useEffect(() => { let active = true; fetchAmbassadorContentTasks().then(rows => { if (active) setTasks(rows); }).catch(() => { if (active) setError("Unable to load your content tasks."); }); return () => { active = false; }; }, []);
  const change = async (task, status) => { try { const updated = await updateAmbassadorContentTask(task._id, { status, postUrl: urls[task._id] || task.postUrl }); setTasks(rows => rows.map(row => row._id === updated._id ? updated : row)); } catch (err) { setError(err.response?.data?.error || "Unable to update task."); } };
  return <section className="ambassador-panel"><h2>My content tasks</h2>{notifications.map(row => <aside key={row._id}><strong>{row.title}</strong><p>{row.message}</p></aside>)}<p>Use the approved assets and instructions below. Lead Porch does not post to your personal accounts.</p>{error && <p role="alert">{error}</p>}{!tasks.length && <p>No content tasks assigned yet.</p>}{tasks.map(task => <article key={task._id}><h3>{task.title}</h3><p>{task.status.replaceAll("_", " ")} · {task.dueAt ? `Due ${new Date(task.dueAt).toLocaleString()}` : "No due date"}</p><p>{task.instructions}</p><p style={{ whiteSpace: "pre-wrap" }}>{task.caption}</p><p>{task.disclosure}</p><p>{task.hashtags.join(" ")}</p><p>{task.platforms.join(" · ")}</p>{task.referralUrl && <a href={task.referralUrl} target="_blank" rel="noreferrer">Your referral link</a>}<button onClick={() => navigator.clipboard.writeText([task.caption, task.disclosure, task.referralUrl].filter(Boolean).join("\n\n")).catch(() => setError("Copy unavailable. Select and copy the caption text."))}>Copy caption</button>{task.media.map(asset => <a key={asset.url} href={asset.url} target="_blank" rel="noreferrer">Open approved media</a>)}{!["completed", "declined"].includes(task.status) ? <div><label>Published post URL<input type="url" value={urls[task._id] || ""} onChange={e => setUrls({ ...urls, [task._id]: e.target.value })}/></label>{task.status === "assigned" && <button onClick={() => change(task, "viewed")}>Mark viewed</button>}{task.status !== "in_progress" && <button onClick={() => change(task, "in_progress")}>Start task</button>}<button onClick={() => change(task, "completed")}>Mark completed</button><button onClick={() => change(task, "declined")}>Decline</button></div> : null}</article>)}</section>;
}
