import { useEffect, useState } from "react";
import Button from "./Button.jsx";
import { createWorkspaceMember, fetchCoachingPrograms, fetchWorkspaceCapabilities, fetchWorkspaceMembers, updateWorkspaceMember } from "../services/api.js";
import "./TeamAccess.css";

const operationalRoles = ["admin", "coach", "closer", "member", "viewer"];
const toggle = (items, value) => items.includes(value) ? items.filter((item) => item !== value) : [...items, value];

export default function TeamAccess({ canManage }) {
  const [members, setMembers] = useState([]), [catalog, setCatalog] = useState({ capabilities: [], roleDefaults: {} }), [programs, setPrograms] = useState([]);
  const [editing, setEditing] = useState(null), [draft, setDraft] = useState(null), [error, setError] = useState(""), [saving, setSaving] = useState(false);
  const [invite, setInvite] = useState({ name: "", email: "", temporaryPassword: "", roles: ["member"] });
  const load = async () => { try { const [team, caps, programRows] = await Promise.all([fetchWorkspaceMembers(), fetchWorkspaceCapabilities(), fetchCoachingPrograms({ limit: 200 })]); setMembers(team.members || []); setCatalog(caps); setPrograms(programRows || []); } catch (err) { setError(err.response?.data?.error || "Unable to load Team & Access."); } };
  useEffect(() => { const initialLoad = window.setTimeout(load, 0); return () => window.clearTimeout(initialLoad); }, []);
  const begin = (member) => { setEditing(member.id); setDraft({ roles: [...member.roles], status: member.status, permissionOverrides: { allow: [...(member.permissionOverrides?.allow || [])], deny: [...(member.permissionOverrides?.deny || [])] }, responsibilities: { programIds: (member.responsibilities?.programIds || []).map(String), applicationProgramIds: (member.responsibilities?.applicationProgramIds || []).map(String), salesPipelineIds: member.responsibilities?.salesPipelineIds || [] } }); };
  const save = async (id) => { try { setSaving(true); const result = await updateWorkspaceMember(id, draft); setMembers((rows) => rows.map((row) => row.id === id ? result.member : row)); setEditing(null); setDraft(null); setError(""); } catch (err) { setError(err.response?.data?.error || "Unable to update team access."); } finally { setSaving(false); } };
  const add = async (event) => { event.preventDefault(); try { setSaving(true); const result = await createWorkspaceMember(invite); setMembers((rows) => [...rows.filter((row) => row.id !== result.member.id), result.member]); setInvite({ name: "", email: "", temporaryPassword: "", roles: ["member"] }); setError(""); } catch (err) { setError(err.response?.data?.error || "Unable to add team member."); } finally { setSaving(false); } };
  return <div className="account-settings-panel account-settings-panel--refined team-access">
    <header><p className="page-eyebrow">Team & Access</p><h2>Roles, permissions, and responsibilities</h2><p>Role defaults establish access. Explicit overrides adjust individual capabilities; record assignments still limit which contacts, students, and opportunities each person can use.</p></header>
    {error ? <p className="form-error">{error}</p> : null}
    <section className="settings-section team-access__members">{members.map((member) => <article key={member.id}>
      <header><span><strong>{member.name}</strong><small>{member.email} · {member.status}</small></span><span>{member.roles.map((role) => <em key={role}>{role}</em>)}</span>{canManage ? <Button variant="outline" size="sm" onClick={() => begin(member)}>Edit access</Button> : null}</header>
      <p><strong>Effective access:</strong> {member.effectivePermissions.length ? member.effectivePermissions.join(" · ") : "No operational capabilities"}</p>
      <p><strong>Coach profile:</strong> {member.roles.includes("coach") ? member.coachProfile?.status || "will be created" : member.coachProfile ? `historical (${member.coachProfile.status})` : "not applicable"} <strong>Sales responsibility:</strong> {member.roles.includes("closer") ? "eligible for assigned opportunities/applications" : "not eligible"}</p>
      {editing === member.id && draft ? <div className="team-access__editor">
        <fieldset><legend>Roles</legend>{operationalRoles.map((role) => <label key={role}><input type="checkbox" checked={draft.roles.includes(role)} onChange={() => setDraft({ ...draft, roles: toggle(draft.roles, role) })} disabled={member.roles.includes("owner") && role === "owner"}/>{role}<small>{(catalog.roleDefaults[role] || []).join(" · ")}</small></label>)}</fieldset>
        <label>Status<select value={draft.status} onChange={(event) => setDraft({ ...draft, status: event.target.value })} disabled={member.roles.includes("owner")}><option value="active">Active</option><option value="suspended">Inactive</option></select></label>
        <fieldset><legend>Explicit capability overrides</legend>{catalog.capabilities.map((capability) => <div key={capability}><span>{capability}</span><label><input type="checkbox" checked={draft.permissionOverrides.allow.includes(capability)} onChange={() => setDraft({ ...draft, permissionOverrides: { ...draft.permissionOverrides, allow: toggle(draft.permissionOverrides.allow, capability), deny: draft.permissionOverrides.deny.filter((item) => item !== capability) } })}/>Allow</label><label><input type="checkbox" checked={draft.permissionOverrides.deny.includes(capability)} onChange={() => setDraft({ ...draft, permissionOverrides: { ...draft.permissionOverrides, deny: toggle(draft.permissionOverrides.deny, capability), allow: draft.permissionOverrides.allow.filter((item) => item !== capability) } })}/>Deny</label></div>)}</fieldset>
        <fieldset><legend>Program responsibilities</legend>{programs.map((program) => <div key={program._id}><span>{program.name}</span><label><input type="checkbox" checked={draft.responsibilities.programIds.includes(String(program._id))} onChange={() => setDraft({ ...draft, responsibilities: { ...draft.responsibilities, programIds: toggle(draft.responsibilities.programIds, String(program._id)) } })}/>Program</label><label><input type="checkbox" checked={draft.responsibilities.applicationProgramIds.includes(String(program._id))} onChange={() => setDraft({ ...draft, responsibilities: { ...draft.responsibilities, applicationProgramIds: toggle(draft.responsibilities.applicationProgramIds, String(program._id)) } })}/>Applications</label></div>)}</fieldset>
        <div><Button loading={saving} onClick={() => save(member.id)}>Save access</Button><Button variant="outline" onClick={() => { setEditing(null); setDraft(null); }}>Cancel</Button></div>
      </div> : null}
    </article>)}</section>
    {canManage ? <form className="settings-section team-access__invite" onSubmit={add}><h3>Add team member</h3><div><label>Name<input value={invite.name} onChange={(event) => setInvite({ ...invite, name: event.target.value })}/></label><label>Email<input type="email" value={invite.email} onChange={(event) => setInvite({ ...invite, email: event.target.value })}/></label><label>Temporary password<input type="password" value={invite.temporaryPassword} onChange={(event) => setInvite({ ...invite, temporaryPassword: event.target.value })}/></label></div><fieldset><legend>Initial roles</legend>{operationalRoles.map((role) => <label key={role}><input type="checkbox" checked={invite.roles.includes(role)} onChange={() => setInvite({ ...invite, roles: toggle(invite.roles, role) })}/>{role}</label>)}</fieldset><Button type="submit" loading={saving} disabled={invite.name.length < 2 || !invite.email.includes("@") || invite.temporaryPassword.length < 12 || !invite.roles.length}>Add team member</Button></form> : null}
  </div>;
}
