import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { FiDollarSign, FiLink, FiUsers } from "react-icons/fi";
import Button from "../components/Button.jsx";
import UserAvatar from "../components/UserAvatar.jsx";
import AmbassadorContentTasks from "../components/AmbassadorContentTasks.jsx";
import { fetchMyAmbassadorPayouts, fetchMyAmbassadorProfile, fetchMyAmbassadorReferrals, updateMyAmbassadorProfile } from "../services/api.js";
import "./AmbassadorPortal.css";
import "./AmbassadorProfile.css";
const money = (amount, currency = "USD") => new Intl.NumberFormat("en-US", { style: "currency", currency }).format((amount || 0) / 100);
const editable = (profile = {}) => ({ displayName: profile.displayName || "", bio: profile.bio || "", publicLocation: profile.publicLocation || "", company: profile.company || "", phone: profile.phone || "", timezone: profile.timezone || "", website: profile.website || "", socialProfiles: { instagram: profile.socialProfiles?.instagram || "", facebook: profile.socialProfiles?.facebook || "", linkedin: profile.socialProfiles?.linkedin || "", x: profile.socialProfiles?.x || "" }, notificationPreferences: { email: profile.notificationPreferences?.email !== false, inApp: profile.notificationPreferences?.inApp !== false } });
export default function AmbassadorPortal() {
  const [profile, setProfile] = useState(null), [referrals, setReferrals] = useState([]), [payouts, setPayouts] = useState([]), [error, setError] = useState(""), [editing, setEditing] = useState(false), [draft, setDraft] = useState(null), [saving, setSaving] = useState(false), [notice, setNotice] = useState("");
  const load = () => Promise.all([fetchMyAmbassadorProfile(), fetchMyAmbassadorReferrals(), fetchMyAmbassadorPayouts()]).then(([a, b, c]) => { setProfile(a); setDraft(editable(a)); setReferrals(b); setPayouts(c); }).catch((err) => setError(err.response?.data?.error || "Unable to load ambassador dashboard."));
  useEffect(() => { load(); }, []);
  const total = (status) => payouts.filter((row) => row.status === status).reduce((sum, row) => sum + row.commissionAmountMinor, 0);
  const save = async () => { setSaving(true); try { const result = await updateMyAmbassadorProfile(draft); setProfile(result); setDraft(editable(result)); setEditing(false); setNotice("Profile saved."); } catch (err) { setError(err.response?.data?.error || "Unable to save profile."); } finally { setSaving(false); } };
  const setSocial = (key, value) => setDraft({ ...draft, socialProfiles: { ...draft.socialProfiles, [key]: value } });
  return <div className="ambassador-page"><header className="ambassador-profile-header"><UserAvatar user={profile?.userId} name={profile?.displayName} size="lg"/><div><p>Brand Ambassador</p><h1>{profile?.displayName || "My ambassador dashboard"}</h1><span>Your referral activity and payout history are private to your account.</span><Link to="/profile">Upload or change headshot</Link></div></header>{error ? <p className="form-error">{error}</p> : null}{notice ? <p className="discovery-notice">{notice}</p> : null}
    <section className="ambassador-panel"><div className="ambassador-profile-complete"><span><strong>Profile {profile?.completeness?.percent || 0}% complete</strong><small>Required: {(profile?.completeness?.requiredFields || []).join(" · ")}</small></span><progress max="100" value={profile?.completeness?.percent || 0}/><Button size="sm" variant="outline" onClick={() => setEditing((value) => !value)}>{editing ? "Cancel" : "Edit profile"}</Button></div>{editing && draft ? <div className="ambassador-profile-form"><label>Display name<input value={draft.displayName} onChange={(e) => setDraft({ ...draft, displayName: e.target.value })}/></label><label>Bio / about<textarea rows="4" value={draft.bio} onChange={(e) => setDraft({ ...draft, bio: e.target.value })}/></label><label>Location<input value={draft.publicLocation} onChange={(e) => setDraft({ ...draft, publicLocation: e.target.value })}/></label><label>Company<input value={draft.company} onChange={(e) => setDraft({ ...draft, company: e.target.value })}/></label><label>Phone<input value={draft.phone} onChange={(e) => setDraft({ ...draft, phone: e.target.value })}/></label><label>Timezone<input value={draft.timezone} onChange={(e) => setDraft({ ...draft, timezone: e.target.value })}/></label><label>Website<input type="url" value={draft.website} onChange={(e) => setDraft({ ...draft, website: e.target.value })}/></label>{["instagram", "facebook", "linkedin", "x"].map((key) => <label key={key}>{key}<input value={draft.socialProfiles[key]} onChange={(e) => setSocial(key, e.target.value)} placeholder="https://… or @handle"/></label>)}<Button loading={saving} onClick={save}>Save profile</Button></div> : null}<p><strong>Referral code:</strong> {profile?.referralCode || "Not configured"} · <strong>Welcome post:</strong> {(profile?.welcomePost?.status || "waiting_for_profile").replaceAll("_", " ")}</p><small>Referral identity, commission settings, role, and account status are managed by Ellie/Admin.</small></section>
    <AmbassadorContentTasks/><section className="ambassador-summary"><article><FiLink/><strong>{profile?.referralCode || "Not configured"}</strong><span>Referral code</span>{profile?.referralUrl ? <a href={profile.referralUrl}>Open referral link</a> : null}</article><article><FiUsers/><strong>{referrals.length}</strong><span>Referred people</span></article><article><FiDollarSign/><strong>{money(total("pending"), payouts[0]?.currency)}</strong><span>Pending payout</span></article><article><FiDollarSign/><strong>{money(total("paid"), payouts[0]?.currency)}</strong><span>Paid history</span></article></section>{profile?.communityUrl ? <section className="ambassador-panel"><h2>Ambassador community</h2><p>This entry point was explicitly enabled for your ambassador profile.</p><a href={profile.communityUrl} target="_blank" rel="noreferrer">Open community</a></section> : null}<section className="ambassador-panel"><h2>My referrals</h2>{referrals.length ? referrals.map((row) => <article className="ambassador-row" key={row._id}><span><strong>{row.contactId?.name || "Referred contact"}</strong><small>{row.attributedAt ? new Date(row.attributedAt).toLocaleDateString() : ""}</small></span><em>{row.state}</em></article>) : <p>No referrals yet.</p>}</section><section className="ambassador-panel"><h2>My payout history</h2>{payouts.length ? payouts.map((row) => <article className="ambassador-row" key={row._id}><span><strong>{money(row.commissionAmountMinor, row.currency)}</strong><small>{row.productLabel || row.contactId?.name || "Referral payout"}</small></span><em>{row.status}</em></article>) : <p>No payouts recorded yet.</p>}</section></div>;
}
