import { useEffect, useState } from "react";
import { FiDollarSign, FiLink, FiUsers } from "react-icons/fi";
import { fetchMyAmbassadorPayouts, fetchMyAmbassadorProfile, fetchMyAmbassadorReferrals } from "../services/api.js";
import "./AmbassadorPortal.css";
const money = (amount, currency = "USD") => new Intl.NumberFormat("en-US", { style: "currency", currency }).format((amount || 0) / 100);
export default function AmbassadorPortal() {
  const [profile, setProfile] = useState(null), [referrals, setReferrals] = useState([]), [payouts, setPayouts] = useState([]), [error, setError] = useState("");
  useEffect(() => { Promise.all([fetchMyAmbassadorProfile(), fetchMyAmbassadorReferrals(), fetchMyAmbassadorPayouts()]).then(([a, b, c]) => { setProfile(a); setReferrals(b); setPayouts(c); }).catch((err) => setError(err.response?.data?.error || "Unable to load ambassador dashboard.")); }, []);
  const total = (status) => payouts.filter((row) => row.status === status).reduce((sum, row) => sum + row.commissionAmountMinor, 0);
  return <div className="ambassador-page"><header><p>Brand Ambassador</p><h1>My ambassador dashboard</h1><span>Your referral activity and payout history are private to your account.</span></header>{error ? <p className="form-error">{error}</p> : null}<section className="ambassador-summary"><article><FiLink/><strong>{profile?.referralCode || "Not configured"}</strong><span>Referral code</span>{profile?.referralUrl ? <a href={profile.referralUrl}>Open referral link</a> : null}</article><article><FiUsers/><strong>{referrals.length}</strong><span>Referred people</span></article><article><FiDollarSign/><strong>{money(total("pending"), payouts[0]?.currency)}</strong><span>Pending payout</span></article><article><FiDollarSign/><strong>{money(total("paid"), payouts[0]?.currency)}</strong><span>Paid history</span></article></section>{profile?.communityUrl ? <section className="ambassador-panel"><h2>Ambassador community</h2><p>This entry point was explicitly enabled for your ambassador profile.</p><a href={profile.communityUrl} target="_blank" rel="noreferrer">Open community</a></section> : null}<section className="ambassador-panel"><h2>My referrals</h2>{referrals.length ? referrals.map((row) => <article className="ambassador-row" key={row._id}><span><strong>{row.contactId?.name || "Referred contact"}</strong><small>{row.attributedAt ? new Date(row.attributedAt).toLocaleDateString() : ""}</small></span><em>{row.state}</em></article>) : <p>No referrals yet.</p>}</section><section className="ambassador-panel"><h2>My payout history</h2>{payouts.length ? payouts.map((row) => <article className="ambassador-row" key={row._id}><span><strong>{money(row.commissionAmountMinor, row.currency)}</strong><small>{row.productLabel || row.contactId?.name || "Referral payout"}</small></span><em>{row.status}</em></article>) : <p>No payouts recorded yet.</p>}</section></div>;
}
