const providers = [
  {
    id: "csv",
    name: "CSV Upload",
    category: "lead_provider",
    description: "Lead import",
    capabilities: ["createContacts", "normalizeContacts"],
    environmentKeys: [],
    builtIn: true,
    availability: "active",
    connectionMethod: "built_in",
    leadDiscovery: true,
  },
  {
    id: "resend",
    name: "Resend",
    category: "communication",
    description: "Email delivery",
    capabilities: ["sendEmail"],
    environmentKeys: ["RESEND_API_KEY"],
    availability: "active",
    connectionMethod: "platform_managed",
    leadDiscovery: false,
  },
  {
    id: "eventbrite",
    name: "Eventbrite",
    category: "events",
    description: "Event data",
    capabilities: ["syncAttendees", "normalizeContacts"],
    environmentKeys: [
      "EVENTBRITE_PRIVATE_TOKEN",
      "EVENTBRITE_CLIENT_ID",
      "EVENTBRITE_CLIENT_SECRET",
    ],
    availability: "active",
    connectionMethod: "customer_oauth",
    leadDiscovery: false,
  },
  {
    id: "meetup",
    name: "Meetup",
    category: "events",
    description: "Public community discovery plus authorized Meetup Pro network and event management",
    capabilities: ["publicCommunityDiscovery", "oauth", "readProNetwork", "readGroups", "readEvents", "readAuthorizedRsvps", "createEventDraft", "updateEvent"],
    environmentKeys: ["MEETUP_CLIENT_ID", "MEETUP_CLIENT_SECRET", "MEETUP_REDIRECT_URI"],
    availability: "configuration_required",
    connectionMethod: "customer_oauth",
    leadDiscovery: false,
    limitation: "Public discovery cannot message a community. Connected actions are limited to assets and data the authorized Meetup Pro account may manage; attendee email is available only when Meetup returns a consented Pro email.",
  },
  {
    id: "linkedin",
    name: "LinkedIn",
    category: "social",
    description: "Customer-authorized LinkedIn Page discovery and publishing",
    capabilities: ["pagePublishing"],
    environmentKeys: ["LINKEDIN_CLIENT_ID", "LINKEDIN_CLIENT_SECRET", "LINKEDIN_REDIRECT_URI", "LINKEDIN_OAUTH_SCOPES", "LINKEDIN_API_VERSION"],
    availability: "configuration_required",
    connectionMethod: "customer_oauth",
    leadDiscovery: false,
    limitation: "LinkedIn does not provide general people search or private group-member export through this connection.",
  },
  {
    id: "facebook",
    name: "Facebook",
    category: "social",
    description: "Authorized Facebook Pages, Messenger, and linked professional Instagram assets",
    capabilities: ["pagePublishing", "pageEngagement", "messaging"],
    environmentKeys: ["META_APP_ID", "META_APP_SECRET", "META_REDIRECT_URI", "FACEBOOK_LOGIN_CONFIG_ID", "META_GRAPH_API_VERSION"],
    availability: "configuration_required",
    connectionMethod: "customer_oauth",
    leadDiscovery: false,
    limitation: "Meta login will manage assets the customer authorizes; it will not expose private groups or member lists.",
  },
  {
    id: "instagram",
    name: "Instagram",
    category: "social",
    description: "Professional Instagram account publishing, comments, and messaging through Instagram Login",
    capabilities: ["publishing", "comments", "messaging"],
    environmentKeys: ["INSTAGRAM_APP_ID", "INSTAGRAM_APP_SECRET", "INSTAGRAM_REDIRECT_URI", "META_GRAPH_API_VERSION"],
    availability: "configuration_required",
    connectionMethod: "customer_oauth",
    leadDiscovery: false,
    limitation: "Uses SocialConnection authorization, not a separate IntegrationConnection. Available actions require granted permissions and account selection; insights sync is not implemented.",
  },
  {
    id: "twilio",
    name: "Twilio",
    category: "communication",
    description: "Consent-aware SMS, MMS, and voice",
    capabilities: ["sendSms", "sendMms", "placeCall", "deliveryEvents", "callRecordingCallbacks"],
    environmentKeys: ["TWILIO_ACCOUNT_SID", "TWILIO_AUTH_TOKEN", "PUBLIC_BACKEND_URL"],
    availability: "configuration_required",
    connectionMethod: "platform_managed",
    leadDiscovery: false,
    limitation: "Number purchase and A2P registration require separate explicit billing and compliance approval.",
  },
  {
    id: "stripe",
    name: "Stripe",
    category: "payments",
    description: "Payments",
    capabilities: ["create", "sync"],
    environmentKeys: ["STRIPE_SECRET_KEY"],
    availability: "planned",
    connectionMethod: "customer_oauth",
    leadDiscovery: false,
  },
  {
    id: "openai",
    name: "OpenAI",
    category: "ai",
    description: "AI intelligence",
    capabilities: ["create"],
    environmentKeys: ["OPENAI_API_KEY"],
    availability: "active",
    connectionMethod: "platform_managed",
    leadDiscovery: false,
  },
];

module.exports = providers;
