const providers = [
  {
    id: "csv",
    name: "CSV Upload",
    category: "lead_provider",
    description: "Lead import",
    capabilities: ["createContacts", "normalizeContacts"],
    environmentKeys: [],
    builtIn: true,
    availability: "active",
    connectionMethod: "built_in",
    leadDiscovery: true,
  },
  {
    id: "resend",
    name: "Resend",
    category: "communication",
    description: "Email delivery",
    capabilities: ["sendEmail"],
    environmentKeys: ["RESEND_API_KEY"],
    availability: "active",
    connectionMethod: "platform_managed",
    leadDiscovery: false,
  },
  {
    id: "eventbrite",
    name: "Eventbrite",
    category: "events",
    description: "Event data",
    capabilities: ["syncAttendees", "normalizeContacts"],
    environmentKeys: [
      "EVENTBRITE_PRIVATE_TOKEN",
      "EVENTBRITE_CLIENT_ID",
      "EVENTBRITE_CLIENT_SECRET",
    ],
    availability: "active",
    connectionMethod: "customer_oauth",
    leadDiscovery: false,
  },
  {
    id: "meetup",
    name: "Meetup",
    category: "events",
    description: "Event distribution",
    capabilities: ["publicCommunityDiscovery"],
    environmentKeys: [],
    availability: "public_only",
    connectionMethod: "none",
    leadDiscovery: false,
    limitation: "Growth Operator can find public Meetup communities. Authenticated Meetup management requires Meetup Pro approval and is not implemented.",
  },
  {
    id: "linkedin",
    name: "LinkedIn",
    category: "social",
    description: "Customer-owned Page publishing, engagement, analytics, and lead-form sync",
    capabilities: ["pagePublishing", "pageEngagement", "leadFormSync"],
    environmentKeys: ["LINKEDIN_CLIENT_ID", "LINKEDIN_CLIENT_SECRET"],
    availability: "planned",
    connectionMethod: "customer_oauth",
    leadDiscovery: false,
    limitation: "LinkedIn does not provide general people search or private group-member export through this connection.",
  },
  {
    id: "facebook",
    name: "Facebook & Instagram",
    category: "social",
    description: "Customer-owned Page publishing, comments, insights, ads, and lead-form sync",
    capabilities: ["pagePublishing", "pageEngagement", "leadFormSync", "adReporting"],
    environmentKeys: ["META_APP_ID", "META_APP_SECRET"],
    availability: "planned",
    connectionMethod: "customer_oauth",
    leadDiscovery: false,
    limitation: "Meta login will manage assets the customer authorizes; it will not expose private groups or member lists.",
  },
  {
    id: "twilio",
    name: "Twilio",
    category: "communication",
    description: "Consent-aware SMS, MMS, and voice",
    capabilities: ["sendSms", "sendMms", "placeCall", "deliveryEvents", "callRecordingCallbacks"],
    environmentKeys: ["TWILIO_ACCOUNT_SID", "TWILIO_AUTH_TOKEN", "PUBLIC_BACKEND_URL"],
    availability: "configuration_required",
    connectionMethod: "platform_managed",
    leadDiscovery: false,
    limitation: "Number purchase and A2P registration require separate explicit billing and compliance approval.",
  },
  {
    id: "stripe",
    name: "Stripe",
    category: "payments",
    description: "Payments",
    capabilities: ["create", "sync"],
    environmentKeys: ["STRIPE_SECRET_KEY"],
    availability: "planned",
    connectionMethod: "customer_oauth",
    leadDiscovery: false,
  },
  {
    id: "openai",
    name: "OpenAI",
    category: "ai",
    description: "AI intelligence",
    capabilities: ["create"],
    environmentKeys: ["OPENAI_API_KEY"],
    availability: "active",
    connectionMethod: "platform_managed",
    leadDiscovery: false,
  },
];

module.exports = providers;
